stages:
  - build
  - staging
  - production

job_build:
  stage: build
  tags:
    - superdev-ci
  script:
    - ansible-playbook -i ./ansible/hosts/build.yml --extra-vars "version=$CI_BUILD_TAG" ./ansible/build.yml
  only:
    - tags

job_staging:
  stage: staging
  tags:
    - superdev-ci
  script:
    - ansible-playbook -i ./ansible/hosts/staging.yml --extra-vars "version=$CI_BUILD_TAG" ./ansible/deploy.yml
  only:
    - tags
  when: on_success

job_production:
  stage: production
  tags:
    - superdev-ci
  script:
    - ansible-playbook -i ./ansible/hosts/production.yml --extra-vars "version=$CI_BUILD_TAG" ./ansible/deploy.yml
  only:
    - tags
  when: manual
